Add a QualityGate to the Sonarqube action
Without this the repo is scanned, however the action still passes if
they are issues

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -37,19 +37,38 @@ jobs:
           - name: Run the unit tests
             run: python -m unittest discover -s ./api/tests -p '*_test.py'
 
-    sonarcloud:
-        runs-on: ubuntu-latest
-        needs: [gitleaks, api-unit-tests]
-        steps:
-          - name: Get the repo
-            uses: actions/checkout@v4
-            with:
-                fetch-depth: 0
-    
-          - name: SonarCloud Scan
-            uses: sonarsource/sonarcloud-github-action@v3.1.0
-            env:
-                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    sonarqube:
+      runs-on: ubuntu-latest
+      needs: [gitleaks, api-unit-tests]
+      steps:
+        - name: Get the repo
+          uses: actions/checkout@v4
+          with:
+            fetch-depth: 0
+
+        # Triggering SonarQube analysis as results of it are required by Quality Gate check.
+        - name: SonarQube Server Scan
+          uses: sonarsource/sonarqube-scan-action@master
+          env:
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+        # Check the Quality Gate status.
+        - name: SonarQube Server Quality Gate check
+          id: sonarqube-quality-gate-check
+          uses: sonarsource/sonarqube-quality-gate-action@master
+          with:
+            pollingTimeoutSec: 600
+          env:
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+        - run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+
+        - name: Quality Gate status check
+          run: |
+            if [[ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" == "FAILED" ]]; then
+              echo "Quality Gate failed"
+              exit 1
+            fi
 
     snyk:
         runs-on: ubuntu-latest
